import Head from 'next/head'
import Link from 'next/link'
import { useState } from 'react'
import styles from '../styles/Home.module.scss'

type HomePageProps = {
  data: Array<{
    name: string,
    url: string
  }>,
  next: string | null,
  previous: string | null
}

export default function HomePage({ data, previous, next }: HomePageProps) {
  const [quantity, setQuantity] = useState(20)
  const [listOfPokemons, setListOfPokemons] = useState(data)
  const [loading, setLoading] = useState(false)

  const changePreviousPage = async () => {
    setLoading(true)
    const res = await fetch(`https://pokeapi.co/api/v2/pokemon?limit=${quantity}&offset=0`)
    const data = await res.json()
    setListOfPokemons(data.results)
    setQuantity(prev => prev + 10)
    setLoading(false)
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.list}>
          <h1>All pokemons</h1>
          {listOfPokemons.map(pokemon => {
            const id = pokemon.url.split('/')[6]
            return <Link href={`/${id}`} key={pokemon.name}>{pokemon.name}</Link>
          })}
        </div>
        <div className={styles.buttonContainer}>
          <button disabled={loading} onClick={changePreviousPage}>MORE</button>
        </div>
      </main>
    </>
  )
}

export async function getStaticProps() {
  const res = await fetch('https://pokeapi.co/api/v2/pokemon?limit=10&offset=0')
  // TYPOWANIE AS
  const data = await res.json()
  return {
    props: {
      data: data.results,
      next: data.next,
      previous: data.previous
    }
  }
}