import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.scss'

type HomePageProps = {
  data: Array<{
    name: string,
    url: string
  }>,
  next: string | null,
  previous: string | null
}

export default function HomePage({ data, previous, next }: HomePageProps) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.list}>
          <h1>All pokemons</h1>
          {data.map(pokemon => {
            const id = pokemon.url.split('/')[6]
            return <Link href={`/${id}`} key={pokemon.name}>{pokemon.name}</Link>
          })}
        </div>
        <div className={styles.buttonContainer}>
          <button disabled={!previous}>prev</button>
          <button disabled={!next}>next</button>
        </div>
      </main>
    </>
  )
}

export async function getStaticProps() {
  const res = await fetch('https://pokeapi.co/api/v2/pokemon?limit=10&offset=0')
  // TYPOWANIE AS
  const data = await res.json()
  return {
    props: {
      data: data.results,
      next: data.next,
      previous: data.previous
    }
  }
}